Git support for create project.

diff --git a/pipelines/initialize_pipeline.yml b/pipelines/initialize_pipeline.yml
--- a/pipelines/initialize_pipeline.yml
+++ b/pipelines/initialize_pipeline.yml
@@ -16,6 +16,15 @@
 
 trigger: none
 
+parameters:
+- name: dadaEnabled
+  displayName: Create as a Develop Anywhere Deploy Anywhere project
+  type: boolean
+  default: false
+- name: dadaGitAccountAlias
+  displayName: DADA Git connection alias
+  type: string
+  default: ''
 
 pool:
   vmImage: ubuntu-latest
@@ -79,7 +88,37 @@ steps:
   workingDirectory: '$(System.DefaultWorkingDirectory)'
   condition: succeeded()
 - script: |
-      set -x
+      dada_enabled=$(echo "${{ parameters.dadaEnabled }}" | tr '[:upper:]' '[:lower:]')
+      echo "##vso[task.setvariable variable=dadaEnabledValue]${dada_enabled}"
+      echo "##vso[task.setvariable variable=dadaGitAccountAliasValue]"
+      echo "##vso[task.setvariable variable=dadaRepositoryUrl]"
+      echo "##vso[task.setvariable variable=dadaBranch]dev"
+
+      if [ "$dada_enabled" != "true" ]; then
+        echo "DADA initialization is disabled."
+        exit 0
+      fi
+
+      dada_git_account_alias="${{ parameters.dadaGitAccountAlias }}"
+      if [ -z "$dada_git_account_alias" ]; then
+        echo "##vso[task.logissue type=error;]DADA Git connection alias is required when DADA initialization is enabled."
+        exit 1
+      fi
+
+      chmod +x ./pipelines/scripts/github/validateDadaRepo.sh
+      dada_repository_url=$(./pipelines/scripts/github/validateDadaRepo.sh \
+        "$(repo_user)" \
+        "$(PAT)" \
+        "$(repoName)" \
+        debug)
+
+      echo "##vso[task.setvariable variable=dadaRepositoryUrl]${dada_repository_url}"
+      echo "##vso[task.setvariable variable=dadaGitAccountAliasValue]${dada_git_account_alias}"
+  displayName: 'Validate DADA repository'
+  workingDirectory: '$(System.DefaultWorkingDirectory)'
+  condition: succeeded()
+- script: |
+      set -e
       cd ../
 
       ########GitHub 
@@ -112,7 +151,14 @@ steps:
         "${LOCAL_DEV_URL}" \
         "$(admin_user)" \
         "$(admin_password)" \
-        "$(repoName)" 2> >(tee >&2))  
+        "$(repoName)" \
+        "" \
+        "$(dadaEnabledValue)" \
+        "$(dadaGitAccountAliasValue)" \
+        "$(dadaRepositoryUrl)" \
+        "$(dadaBranch)" \
+        "" \
+        "debug" 2> >(tee >&2))
         echo "Captured Project ID: [$project_id]"
         ./self/pipelines/scripts/github/commitProjectConfig.sh "$(repoName)" "project-config" ".project.project-id" "$project_id" "${HOME_DIR}" true "$(devUser)" "$(featureBranchName)" debug
         ./self/pipelines/scripts/github/commitProjectConfig.sh "$(repoName)" "project-config" ".project.project-name" "$(repoName)" "${HOME_DIR}" true "$(devUser)" "$(featureBranchName)" debug
@@ -154,7 +200,14 @@ steps:
               "${LOCAL_DEV_URL}" \
               "$(admin_user)" \
               "$(admin_password)" \
-              "$(repoName)" 2> >(tee >&2))  
+              "$(repoName)" \
+              "" \
+              "$(dadaEnabledValue)" \
+              "$(dadaGitAccountAliasValue)" \
+              "$(dadaRepositoryUrl)" \
+              "$(dadaBranch)" \
+              "" \
+              "debug" 2> >(tee >&2))
               echo "Captured Project ID: [$project_id]"
               # Import (align with synchronizeDEV: include provider/Azure params)
               echo "Importing asset ..."
@@ -167,5 +220,3 @@ steps:
       fi
   displayName: 'Create / Sychronize the projects'
   condition: succeeded()
-
-  
